DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL
);



INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'B1234', 'JUAN', 'PEREZ');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'C5678', 'MARIO', 'GOMEZ');